version: '3.4'

services:
  apipagos:
    image: ${DOCKER_REGISTRY-}apipagos
    ports: 
        - 5010:80
        - 5011:443      
    build:
      context: .
      dockerfile: API Pagos/Dockerfile
  api:
    image: ${DOCKER_REGISTRY-}api
    ports: 
        - 5000:80
        - 5001:443 
    build:
        context: .
        dockerfile: API/Dockerfile
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=Abc*123!
      - ACCEPT_EULA=Y
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data: